### ISSUE TITLE
Setting of epoch

### ISSUE THREAD

**Issue by forkliu0826** [yfqiu-nlp/hiergnn#2]
Hello, the program I run here will end with one epoch. I see that there are 10 epochs in your operation document. Would you like to know how to modify it？

**Comment by yfqiu98** [comment]
Hi, the trainer behaviour is supposed to train the model with 10 epochs and save checkpoint at each epoch and last_checkpoint&best_checkpoint after the final step.

**Comment by forkliu0826** [comment]
Thank you for your answer. I have another question, that is, I have reproduced your experimental results, and the results are low,mid and high. May I ask which index is corresponding to paper rouge?

**Comment by yfqiu98** [comment]
Please use mid for fair comparison. See here for more details: https://github.com/google-research/google-research/issues/294#issuecomment-652262191.
